### ISSUE TITLE
Server crash on loading mod

### ISSUE THREAD

**Issue by Ironsoupbowl** [itzme1on/AlcoCraft-Plus#4] opened 2023-04-24 01:33 UTC
I do not know much of the in and outs of modding forge servers, but I was hoping to be able to put this mod onto my 1.19.2 server. So I through it in and while my client instance opened just fine, the server encountered the following crash which does not happen when the mod is removed:

        Crash Report UUID: af3b25e4-3aa0-4f9e-8291-97c67e075029
        FML: 43.2
        Forge: net.minecraftforge:43.2.8[20:13:54] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Alcocraft (alcocraftplus) has failed to load correctly
?7java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER

Some minor searching on my part lead to some discussion of similar crashes, but most were about having client exclusive mods like locus and other optifine alternatives on the server mod list. The full log is attached.

Any help would be appreciated, thank you for maintaining this mod and thank you for your time.
[Alcocraft Crash Error Log.txt](https://github.com/itzme1on/AlcoCraft-Plus/files/11305590/Alcocraft.Crash.Error.Log.txt)

**Comment by itzme1on** [comment] 2023-04-24 06:00
Have you used hadrus' mod before (AlcoCraft: Beer and stuff)? It is strange that the class `net.hadrus.alcocraft.AlcoCraftPlus` is specified in the console. AlcoCraft+ registries methods are in another package (https://github.com/itzme1on/AlcoCraft-Plus/blob/6211da457728f5201454f9528c4adc4392191d9a/src/main/java/me/itzme1on/alcocraftplus/AlcoCraftPlus.java#L28)

**Comment by itzme1on** [comment] 2023-04-24 19:30
Oh, no, I'm wrong. After all, the packages in version 1.19.2 do not correspond to the packages from version 1.18.2
Send me your mods list, please

**Comment by Ironsoupbowl** [comment] 2023-04-24 19:37
I have not used the original mod before. Friends of mine thought it sounded cool and noticed that you recently updated it to 1.19.2.

What I am running is a server pack from Create Re-flavored with a few additions like ars nouveau and some dungeons mods. Even with those mods slapped in the server runs fine, just when I add in yours I get that issue.

I won't be back from work for another few hours. The mods list is in the server log towards the 2/3rds mark I believe. I'll send the proper edited down modlist when I can.
Thanks.

**Comment by itzme1on** [comment] 2023-04-24 19:39
Okay, let me check the code and try to run the server with my mod, and then I'll try to help you.

**Comment by itzme1on** [comment] 2023-04-24 19:44
At least now I'm porting the mod using the Architectury API, and in the future the development will move faster. The problem is that it is very difficult to register a keg in Fabric, because a lot of methods and logic from Forge are taken there, and I am not a professional in creating mods, so I apologize in advance for the occurrence of bugs :(

**Comment by Ironsoupbowl** [comment] 2023-04-24 20:19
All is well. I appreciate the effort and hate that I introduced the problem I'm having to you but I would love to get your mod working.

If this isn't just something stupid on my end, then I hope that someone else is spared the trouble further down the line.

**Comment by Ironsoupbowl** [comment] 2023-04-25 11:15
Sorry for the delay in case you didn't get the modlist from the server log.

        Mod List:
                maenchants-1.19.2-6.0.0.jar  
                YungsBetterDungeons-1.19.2-Forge-3.2.2.jar  
                create_misc_and_things_1.19.2_2.0.jar  
                supermartijn642configlib-1.1.6b-forge-mc1.19.jar 
                v_slab_compat-1.19.2-1.4.jar  
                open-parties-and-claims-forge-1.19.2-0.17.2.jar 
                infernal-expansion-1.19.2-2.5.3.jar   
                player-animation-lib-forge-1.0.2.jar 
                Aquamirae Mod EXTRA Music.jar   
                naturalist-forge-2.1.1-1.19.2.jar  
                HealthOverlay-1.19.2-7.2.1.jar 
                incontrol-1.19-7.1.3.jar
                YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar 
                Potato-Canon-Plus_1.19.2_Forge_V1.0.jar 
                immersive_aircraft-0.4.2+1.19.2-forge.jar 
                sophisticatedcore-1.19.2-0.5.49.245.jar  
                XaerosWorldMap_1.29.5_Forge_1.19.1.jar
                CTM-1.19.2-1.1.6+8.jar
                citadel-2.1.3-1.19.jar    
                YungsApi-1.19.2-Forge-3.8.9.jar
                mixinextras-forge-0.2.0-beta.6.jar
                moreminecarts-1.5.7.jar     
                sophisticatedbackpacks-1.19.2-3.18.44.815.jar  
                littlecontraptions-forge-1.19.2.0.jar
                guardvillagers-1.19.2-1.5.5.jar  
                create_dragon_lib-1.19.2-1.1.2.jar  
                forgivingvoid-forge-1.19-7.0.0.jar 
                takesapillage-1.0.3-1.19.2.jar 
                balm-forge-1.19.2-4.5.7.jar  
                JustEnoughResources-1.19.2-1.1.0.179.jar
                YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar
                dragonfight-1.19.2-2.5.jar   
                cloth-config-8.2.88-forge.jar    
                konkrete_forge_1.6.0_MC_1.19-1.19.2.jar
                geophilic?1.19-2.0.0.jar          
                createcafe-1.1.5-1.19.2.jar      
                upgradednetherite-1.19.2-5.1.0.7-release.jar 
                easy_piglins-1.19.2-1.0.0.jar         
                chipped-forge-1.19.2-2.1.4.jar    
                FarmersDelight-1.19-1.2.0.jar     
                torchmaster-19.2.0.jar        
                handcrafted-forge-1.19.2-2.0.6.jar
                DustrialDecor-1.3.3-1.19.2.jar  
                Good Ending-1.19.2-1.0.2-forge.jar   
                UnusualEnd1.19_V1.2.7.jar      
                supermartijn642corelib-1.1.7-forge-mc1.19.jar  
                YungsBridges-1.19.2-Forge-3.1.0.jar  
                resourcefulconfig-forge-1.19.2-1.0.20.jar
                cloudstorage-1.3.4-1.19.2.jar
                wthit-forge-5.15.2.jar  
                goprone-1.19-2.0.4.jar          
                lightspeed-1.19.2-1.0.3.jar   
                curios-forge-1.19.2-5.1.4.0.jar  
                tetra-1.19.2-5.2.1.jar   
                Patchouli-1.19.2-77.jar
                solsweetpotato-1.19.2-2.0.0.jar 
                collective-1.19.2-6.53.jar  
                simplehats-forge-1.19.2-0.1.6.jar  
                OreExcavation-1.11.166.jar    
                YungsExtras-1.19.2-Forge-3.1.0.jar 
                bettervillage-forge-1.19.2-3.1.0.jar
                YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar  
                resourcefullib-forge-1.19.2-1.1.24.jar  
                starterkit-1.19.2-5.2.jar 
                lootjs-forge-1.19.2-2.8.0.jar  
                littlelogistics-mc1.19.2-v1.3.2.jar  
                architectury-6.5.77-forge.jar  
                AI-Improvements-1.19.2-0.5.2.jar   
                create_crystal_clear-0.1.2e-1.19.2.jar  
                AgeingSpawners-1.19.2-1.2.2.jar  
                extendedflywheels-1.2.5-1.19.2-0.5.f.jar 
                trashcans-1.0.17a-forge-mc1.19.jar 
                create-chromaticreturn1.19.2_v1.0.2.jar 
                toms_storage-1.19-1.5.4.jar  
                strayspawn-1.19.2-3.3.jar 
                Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar   
                FastLeafDecay-30.jar 
                YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar 
                geckolib-forge-1.19-3.1.40.jar 
                createteleporters0.6.1.jar
                sliceanddice-2.0.3.jar  
                effortlessbuilding-1.19-2.40.jar 
                QuarkOddities-1.18.jar    
                rhino-forge-1902.2.2-build.268.jar 
                Fastload-Reforged-2.6.9+1.19.2.jar 
                biomemakeover-FORGE-1.19.2-1.6.4.jar 
                sophisticatedstorage-1.19.2-0.6.26.325.jar 
                redstonepen-1.19.2-forge-1.2.20.jar 
                jei-1.19.2-forge-11.6.0.1015.jar 
                kubejs-forge-1902.6.0-build.142.jar 
                AttributeFix-Forge-1.19.2-17.2.6.jar 
                TravelAnchors-1.19.2-4.1.2.jar 
                libraryferret-forge-1.19.2-4.0.0.jar
                Paxi-1.19.2-Forge-3.0.1.jar  
                obscure_api-14.jar                   
                Clumps-forge-1.19.2-9.0.0+14.jar
                integrated_api_forge-1.2.7+1.19.2.jar 
                SimpleStorageNetwork-1.19-1.6.5.jar 
                configured-2.1.1-1.19.2.jar  
                badpackets-forge-0.2.1.jar 
                LibX-1.19.2-4.2.8.jar 
                Decorative Blocks-forge-1.19.2-3.0.0.jar 
                DungeonCrawl-1.19-2.3.12.jar  
                create-confectionery1.19.2_v1.0.8.jar 
                lazydfu-1.19-1.0.2.jar   
                starlight-1.1.1+forge.cf5b10b.jar
                everycomp-1.19.2-2.3.3.jar 
                YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar 
                tetratic-combat-1.19-2.6.jar
                Terralith_1.19.3_v2.3.7b.jar
                blueprint-1.19.2-6.1.2.jar 
                environmental-1.19.2-3.0.0.jar  
                savage_and_ravage-1.19.2-5.0.4.jar  
                ars_nouveau-1.19.2-3.13.1.jar
                forge-1.19.2-43.2.8-universal.jar
                castle_dungeons-3.3-1.19-forge.jar
                Raided-1.19.2-0.1.3.jar 
                xercamusic-1.19.2-1.1.0.jar 
                neapolitan-1.19.2-4.0.2.jar 
                idas_forge-1.7.0+1.19.2.jar  
                alcocraftplus-1.19.2-forge-1.0.jar 
                infernalmobs-1.19.2.4.jar
                DungeonsArise-1.19.2-2.1.55-beta.jar 
                craftingtweaks-forge-1.19-15.1.6.jar
                server-1.19.2-20220805.130853-srg.jar
                TerraBlender-forge-1.19.2-2.0.1.136.jar
                swingthroughgrass-1.19.2-1.10.0.jar
                moonlight-1.19.2-2.2.31-forge.jar
                nohostilesaroundcampfire-1.19.2-5.4.jar
                bettercombat-forge-1.6.2+1.19.jar 
                netherdungeons-1.0.jar  
                DiceMC Money-1.19.2-0.0.2.jar   
                NoChatReports-FORGE-1.19.2-v1.5.1.jar 
                another_furniture-forge-2.1.2-1.19.2.jar
                CreativeCore_FORGE_v2.9.3_mc1.19.2.jar 
                NethersDelight-1.19-3.0.jar 
                collectorsreap-1.19-1.2.3.jar 
                createendertransmission-1.2.1.jar 
                atmospheric-1.19.2-5.0.0.jar
                kffmod-3.11.0.jar 
                rottencreatures-forge-1.19.2-1.0.1.jar 
                easy_villagers-1.19.2-1.0.7.jar 
                flywheel-forge-1.19.2-0.6.8.a.jar 
                create-1.19.2-0.5.0.i.jar 
                createdeco-1.3.0-1.19.2.jar  
                create_central_kitchen-1.19.2-for-create-0.5.0.i-1|Create: Central Kitchen
                create_mechanical_extruder-1.19.2-1.3.2.i.jar  
                Steam_Rails-1.19.2-1.1.1.jar 
                liquidburner-1.19.2-0.3a.jar  
                extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar|Extended Cogwheels
                CreateCasing-1.19.2-1.1.2-hotfix-1.jar
                mutil-1.19.2-5.1.0.jar  
                ecologics-forge-1.19.2-2.1.11.jar
                Xaeros_Minimap_23.3.3_Forge_1.19.1.jar  
                gravestone-1.19.2-1.0.1.jar   
                create-stuff-additions1.19.2_v2.0.2c.jar
                AutoRegLib-1.8.2-55.jar 
                Quark-3.4-397.jar 
                supplementaries-1.19.2-2.3.4.jar
                DramaticDoors-Forge-1.19.2-2.1.10.jar   
                abnormals_delight-1.19.2-4.0.2.jar       
                DiagonalFences-v4.2.3-1.19.2-Forge.jar 
                crittersandcompanions-1.19.2-1.1.2.jar    
                upgradedcore-1.19.2-4.1.0.1-release.jar 
                kubejs-create-forge-1902.1.1-build.35.jar 
                ImmediatelyFastReforged-1.19.2-1.1.12.jar
                creeperoverhaul-2.0.9-forge.jar 
                appleskin-forge-mc1.19-2.4.2.jar
                ferritecore-5.0.3-forge.jar
                upgradednetherite_ultimate-1.19.2-4.1.0.3-release
                PuzzlesLib-v4.3.12-1.19.2-Forge.jar
                Lychee-1.19.2-forge-3.10.0.jar
                extremesoundmuffler-3.37-forge-1.19.2.jar
                Delightful-1.19.2-3.2.4.jar
                CosmeticArmorReworked-1.19.2-v1a.jar
                create_enchantment_industry-1.19.2-for-create-0.5.
                aquamirae-5.6.API14.jar
                createaddition-1.19.2-20230411a.jar 
                defaultoptions-forge-1.19-15.0.1.jar

**Comment by Arathorne** [comment] 2023-04-30 10:53
Hello, i also have the same error when launching a server with alcocraft
![obraz](https://user-images.githubusercontent.com/60345302/235349131-7f6db656-2855-41e9-bb85-a55150b15303.png)
![obraz](https://user-images.githubusercontent.com/60345302/235349141-6cb38d9a-0c1b-4679-94bf-5ac45b2592a3.png)

**Comment by da-batt** [comment] 2023-05-03 09:51
Fixed in #5

**Comment by itzme1on** [comment] 2023-05-03 09:55
Guys, I'm really sorry for not responding to issues. I am insanely busy with work, I have two large orders and I have to work 9-11 hours a day. I will definitely take the time to sort everything out. 

You can join my discord to keep us in touch (https://discord.gg/Qsr8cAdjxW)

**Comment by itzme1on** [comment] 2023-05-03 09:55
> Fixed in #5

@david-frederick-batt, thank you, i will check it today and publish new version to CurseForge and Modrinth. PM me in Discord

**Comment by Wolfstar1010** [comment] 2023-05-05 01:50
Hi just wondering if this has been fixed? Having the same issue.

**Comment by itzme1on** [comment] 2023-05-05 14:41
That was fixed in #5. You can download fixed version on [Modrinth](https://modrinth.com/mod/alcocraft/version/1.0.1+1.19.2) and [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/alcocraft/files/4523307) (clickable links).

**Closed as completed by itzme1on** 2023-05-05 14:41 UTC
